name: tdd_sampel
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  http: ^0.13.5
  get_it: ^7.2.0
  injectable: ^1.5.3
  internet_connection_checker: ^0.0.1+4
  equatable: ^2.0.3
  dartz: ^0.10.1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  bloc_test: ^9.0.3
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  json_serializable: ^6.3.1
  freezed: ^2.1.0+1
  mockito: ^5.3.0
  mocktail: ^0.3.0
  injectable_generator: ^1.5.4


flutter:


  uses-material-design: true

